use anyhow::{Context, Result, bail};
use std::path::Path;
use wasm_encoder::{
    CodeSection, ConstExpr, CustomSection, DataSection, ExportKind, ExportSection, Function,
    FunctionSection, Ieee32, Ieee64, Instruction, MemorySection, MemoryType, Module, ValType,
};
use wasm_metadata::Producers;
use wasm_wave::untyped::UntypedValue;
use wit_component::{ComponentEncoder, DecodedWasm, StringEncoding, metadata};
use wit_parser::abi::{AbiVariant, WasmSignature, WasmType};
use wit_parser::{
    FunctionKind, LiftLowerAbi, ManglingAndAbi, Resolve, WasmExport, WasmExportKind, WorldId,
    WorldItem, WorldKey,
};

use values::{Flat, Layout, optional_fields, parser_error};
use wasm_wave::ast::Node;

mod docs;
mod expr;
mod streams;
pub mod types;
mod values;

/// Values for [`Overrides::Value`], from `wasm_wave`.
///
/// Values are built with the [`WasmValue`](value::WasmValue) constructors,
/// e.g. [`Value::make_record`](value::WasmValue::make_record), from types
/// built with [`Type`](value::Type).
pub mod value {
    pub use wasm_wave::value::{Type, Value};
    pub use wasm_wave::wasm::{WasmValue, WasmValueError};
}

/// Address where constant data starts in linear memory. Kept non-zero so a
/// valid pointer is never null.
const DATA_BASE: u32 = 8;
const PAGE_SIZE: u64 = 65536;

/// Parses WIT from a file or directory and selects a world from it.
///
/// When `world` is `None`, the package must contain exactly one world.
pub fn load_world(path: impl AsRef<Path>, world: Option<&str>) -> Result<(Resolve, WorldId)> {
    let mut resolve = Resolve::default();
    let (pkg, _) = resolve.push_path(path)?;
    let world = resolve.select_world(&[pkg], world)?;
    Ok((resolve, world))
}

/// Parses WIT text and selects a world from it. Packages the world depends on
/// may be defined inline with nested `package ns:name { ... }` blocks.
///
/// When `world` is `None`, the package must contain exactly one world.
pub fn parse_world(text: &str, world: Option<&str>) -> Result<(Resolve, WorldId)> {
    let mut resolve = Resolve::default();
    let pkg = resolve.push_str("input.wit", text)?;
    let world = resolve.select_world(&[pkg], world)?;
    Ok((resolve, world))
}

/// Decodes a WIT package encoded as wasm and selects a world from it.
///
/// When `world` is `None`, the package must contain exactly one world.
pub fn decode_world(bytes: &[u8], world: Option<&str>) -> Result<(Resolve, WorldId)> {
    match wit_component::decode(bytes)? {
        DecodedWasm::WitPackage(resolve, pkg) => {
            let world = resolve.select_world(&[pkg], world)?;
            Ok((resolve, world))
        }
        DecodedWasm::Component(..) => bail!("expected a WIT package, found a component"),
    }
}

/// Creates a component that implements every export of `world` by returning a
/// constant value.
///
/// The world may only export functions (directly, or within interfaces) that
/// take no parameters, synchronous or async. Their values may not reach
/// resources, handles, futures, streams, error contexts or maps, though the
/// result types may include them in branches the values don't take, e.g.
/// `none` for an `option<own<r>>`. Types the exports reference from other
/// interfaces become imports of the resulting component.
///
/// A function may return a `stream<T>`, whose value is a list of the stream's
/// items. Only an async function can return a stream with items, which it
/// writes as they're read. Any function can return an empty stream, `[]`.
/// A stream of integers, floats or `bool` may continue with items generated by
/// a closure following an `@expression` tag, from the items before them:
///
/// ```wit
/// /// @value [1, 1]
/// /// @expression |a, b| a + b
/// fibonacci: async func() -> stream<u32>;
/// ```
///
/// The stream ends once an item can't be represented, e.g. on overflow.
/// Instead of a `@value`, an async function may take the items the stream
/// starts from as arguments, one for each of the closure's parameters, e.g.
/// `async func(a: u32, b: u32) -> stream<u32>`.
///
/// Each function's value is a WAVE expression following a `@value` tag in its
/// doc comment:
///
/// ```wit
/// /// The answer to everything.
/// /// @value 42
/// answer: func() -> u32;
/// ```
///
/// `overrides`, when provided, replaces values from the WIT, see [`Overrides`].
pub fn create_component(
    resolve: &Resolve,
    world: WorldId,
    overrides: Option<Overrides>,
) -> Result<Vec<u8>> {
    let module = create_module(resolve, world, overrides)?;
    ComponentEncoder::default()
        .validate(true)
        .module(&module)?
        .encode()
}

/// Values replacing those from the WIT.
///
/// The overrides are a record with a field per world export. A function
/// export's field holds its value, and an interface export's field (named by
/// the interface) holds a nested record with a field per function. Every field
/// is optional:
///
/// ```text
/// {
///   answer: 42,
///   constants: {
///     origin: {x: 0, y: 0},
///   },
/// }
/// ```
#[derive(Debug, Clone, Copy)]
#[non_exhaustive]
pub enum Overrides<'a> {
    /// The record as WAVE source, `//` line comments are allowed. Source with
    /// nothing but whitespace and comments overrides nothing.
    Wave(&'a str),
    /// The record as a value, e.g. built with
    /// [`WasmValue::make_record`](value::WasmValue::make_record).
    /// The record's type only needs the fields being overridden.
    Value(&'a value::Value),
}

/// An exported function, the interface it belongs to, and its value.
struct Constant<'a> {
    interface: Option<&'a WorldKey>,
    func: &'a wit_parser::Function,
    src: &'a str,
    value: Value<'a>,
}

enum Value<'a> {
    Override(&'a Node),
    Doc(UntypedValue<'a>),
    /// A stream generated from the function's arguments.
    Arguments,
}

/// What a constant's function returns.
enum Body<'a> {
    /// Flat values, or a pointer to the value in memory.
    Flat(WasmSignature, Vec<Flat>),
    /// A stream of items in memory.
    Stream(streams::Stream<'a>),
}

impl Constant<'_> {
    fn node(&self) -> Option<&Node> {
        match &self.value {
            Value::Override(node) => Some(node),
            Value::Doc(value) => Some(value.node()),
            Value::Arguments => None,
        }
    }
}

fn create_module(
    resolve: &Resolve,
    world: WorldId,
    overrides: Option<Overrides>,
) -> Result<Vec<u8>> {
    // every export must be a function returning a supported type
    let exports = &resolve.worlds[world].exports;
    let mut labels = vec![];
    for (key, item) in exports {
        let label = export_label(resolve, key)?;
        match item {
            WorldItem::Function(func) => types::check_function(func)?,
            WorldItem::Interface { id, .. } => {
                for func in resolve.interfaces[*id].functions.values() {
                    types::check_function(func).with_context(|| format!("interface `{label}`"))?;
                }
            }
            WorldItem::Type { .. } => bail!("worlds may not export types"),
        }
        if labels.contains(&label) {
            bail!("multiple exports are named `{label}`");
        }
        labels.push(label);
    }

    // match overrides to exports, values are written as WAVE to share its
    // parsing and type checking
    let written;
    let overrides_src = match overrides {
        None => "",
        Some(Overrides::Wave(src)) if is_blank(src) => "",
        Some(Overrides::Wave(src)) => src,
        Some(Overrides::Value(value)) => {
            written = wasm_wave::to_string(value).context("invalid overrides")?;
            &written
        }
    };
    let overrides = match overrides_src {
        "" => None,
        src => Some(
            UntypedValue::parse(src)
                .map_err(|e| parser_error(src, e))
                .context("invalid overrides")?,
        ),
    };
    let labels: Vec<&str> = labels.iter().map(String::as_str).collect();
    let export_overrides = match &overrides {
        Some(value) => {
            optional_fields(overrides_src, value.node(), &labels).context("invalid overrides")?
        }
        None => vec![None; labels.len()],
    };

    // pair each exported function with its override or its `@value` doc
    let mut constants = vec![];
    for (((key, item), label), node) in exports.iter().zip(labels).zip(export_overrides) {
        let funcs = match item {
            WorldItem::Function(func) => vec![(None, func, node)],
            WorldItem::Interface { id, .. } => {
                let funcs = &resolve.interfaces[*id].functions;
                let names: Vec<&str> = funcs.keys().map(String::as_str).collect();
                let nodes = match node {
                    Some(node) => optional_fields(overrides_src, node, &names)
                        .with_context(|| format!("invalid overrides for interface `{label}`"))?,
                    None => vec![None; names.len()],
                };
                funcs
                    .values()
                    .zip(nodes)
                    .map(|(f, n)| (Some(key), f, n))
                    .collect()
            }
            WorldItem::Type { .. } => unreachable!(),
        };
        for (interface, func, node) in funcs {
            let name = qualified_name(resolve, interface, func);
            let location = resolve.source_map.render_location(func.span);
            // a stream generated from the arguments has no value of its own
            if !func.params.is_empty() {
                if node.is_some() {
                    bail!(
                        "invalid overrides: `{name}` can't be overridden, its stream is \
                         generated from its arguments"
                    );
                }
                // an expression reading `$init` may also list the items it starts
                // from, otherwise the arguments are the items it starts from. An
                // expression that doesn't parse is reported with its own error.
                let args = arg_names(func);
                let uses_seed = docs::expression(&func.docs).is_some_and(|src| {
                    expr::parse_closure(src.trim(), &args).map_or(true, |closure| closure.uses_seed)
                });
                let constant = match (docs::value(&func.docs), uses_seed) {
                    (Some(_), false) => bail!(
                        "invalid `{}` for `{name}` at {location}: its stream starts from its \
                         arguments, remove the tag, or read the arguments with `$init`",
                        docs::TAG
                    ),
                    (Some(src), true) => Constant {
                        interface,
                        func,
                        src,
                        value: Value::Doc(
                            UntypedValue::parse(src)
                                .map_err(|e| parser_error(src, e))
                                .with_context(|| {
                                    format!("invalid `{}` for `{name}` at {location}", docs::TAG)
                                })?,
                        ),
                    },
                    (None, _) => Constant {
                        interface,
                        func,
                        src: "",
                        value: Value::Arguments,
                    },
                };
                constants.push(constant);
                continue;
            }
            let constant = match (node, docs::value(&func.docs)) {
                (Some(node), _) => Constant {
                    interface,
                    func,
                    src: overrides_src,
                    value: Value::Override(node),
                },
                (None, Some(src)) => Constant {
                    interface,
                    func,
                    src,
                    value: Value::Doc(
                        UntypedValue::parse(src)
                            .map_err(|e| parser_error(src, e))
                            .with_context(|| {
                                format!("invalid `{}` for `{name}` at {location}", docs::TAG)
                            })?,
                    ),
                },
                (None, None) => bail!(
                    "missing value for `{name}` at {location}: add a `{}` tag to its doc \
                     comment, or an override",
                    docs::TAG
                ),
            };
            constants.push(constant);
        }
    }

    // encode the values, the flat values each function returns or the items of
    // the stream it returns
    let mut layout = Layout::new(resolve, DATA_BASE)?;
    let mut bodies = vec![];
    for constant in &constants {
        let func = constant.func;
        let ty = func.result.as_ref().expect("checked by check_function");
        let sig = resolve.wasm_signature(AbiVariant::GuestExport, func);
        let node = constant.node();
        let context = || {
            let name = qualified_name(resolve, constant.interface, func);
            match constant.value {
                Value::Override(_) => format!("invalid override for `{name}`"),
                Value::Doc(_) | Value::Arguments => format!(
                    "invalid `{}` for `{name}` at {}",
                    docs::TAG,
                    resolve.source_map.render_location(func.span)
                ),
            }
        };
        layout.set_source(constant.src);

        // an expression always comes from the WIT, overrides only replace the
        // items it starts from
        let expression = docs::expression(&func.docs);
        let expression_context = || {
            format!(
                "invalid `{}` for `{}` at {}",
                docs::EXPRESSION_TAG,
                qualified_name(resolve, constant.interface, func),
                resolve.source_map.render_location(func.span)
            )
        };
        let stream = streams::stream_type(resolve, ty);
        if expression.is_some() && stream.is_none() {
            return Err(anyhow::anyhow!(
                "only functions returning a stream can generate items"
            ))
            .with_context(expression_context);
        }

        let body = if let Some((stream_ty, item)) = stream {
            let closure = match expression {
                Some(src) => Some(
                    expr::parse_closure(src.trim(), &arg_names(func))
                        .with_context(expression_context)?,
                ),
                None => None,
            };
            let uses_seed = closure.as_ref().is_some_and(|closure| closure.uses_seed);
            let generator = match closure {
                Some(closure) => {
                    let prim = expr::Prim::from_type(resolve, &item)
                        .context("only streams of integers, floats or bool can generate items")
                        .with_context(expression_context)?;
                    let seeds = match uses_seed {
                        true => seed_types(resolve, func).with_context(expression_context)?,
                        false => vec![],
                    };
                    // `$init`'s fields by name, as Rust names the parameters
                    let names = arg_names(func);
                    Some(
                        closure
                            .check(prim, &seeds, &names)
                            .with_context(expression_context)?,
                    )
                }
                None => None,
            };
            if !func.params.is_empty() && !uses_seed {
                // a stream starting from the function's arguments
                let generator = generator.expect("parameters require an expression");
                let stream =
                    arguments_stream(resolve, constant.interface, func, stream_ty, generator)
                        .with_context(expression_context)?;
                bodies.push(Body::Stream(stream));
                continue;
            }
            if uses_seed {
                check_arguments(resolve, func).with_context(expression_context)?;
            }
            // the listed items, or none for a stream generated from `$init` without
            // a `@value`
            let (ptr, len, stride) = match (node, &generator) {
                (Some(node), _) => layout.stream(&item, node).with_context(context)?,
                (None, Some(generator)) => (0, 0, generator.item.size()),
                (None, None) => unreachable!("only generated streams lack a value"),
            };
            let generates = generator.is_some();
            if let Some(node) = node
                && (len > 0 || generates)
                && !matches!(func.kind, FunctionKind::AsyncFreestanding)
            {
                return Err(layout.stream_requires_async(node)).with_context(context);
            }
            if let Some(generator) = &generator
                && len < generator.params
            {
                return match node {
                    Some(node) => Err(layout.too_few_items(node, generator.params)),
                    None => Err(anyhow::anyhow!(
                        "the expression reads the previous {n} items, list at least {n} with \
                         `{}`",
                        docs::TAG,
                        n = generator.params
                    )),
                }
                .with_context(context);
            }
            Body::Stream(streams::Stream {
                interface: constant.interface,
                func,
                ty: stream_ty,
                ptr,
                len,
                stride,
                args: 0,
                generator,
            })
        } else {
            let node = node.expect("only streams are generated from arguments");
            if sig.retptr {
                let flat = vec![Flat::I32(
                    layout.store_new(ty, node).with_context(context)? as i32
                )];
                Body::Flat(sig, flat)
            } else {
                let mut flat = vec![];
                layout.flatten(ty, node, &mut flat).with_context(context)?;
                Body::Flat(sig, flat)
            }
        };
        bodies.push(body);
    }

    // streams import intrinsics, which come first in the function index space,
    // and add helper functions following the constants
    let streams: Vec<&streams::Stream> = bodies
        .iter()
        .filter_map(|body| match body {
            Body::Stream(stream) => Some(stream),
            Body::Flat(..) => None,
        })
        .collect();
    let mut types = streams::Types::new();
    let mut imports = streams::Imports::new();
    for body in &bodies {
        match body {
            Body::Flat(sig, _) => {
                let results: Vec<ValType> = sig.results.iter().map(val_type).collect();
                types.push(&[], &results);
            }
            // the arguments a stream starts from, returning its readable end or
            // an async callback code
            Body::Stream(stream) => {
                types.push(&stream.params(), &[ValType::I32]);
            }
        }
    }
    let plan = streams::Plan::new(resolve, &streams, &mut types, &mut imports);
    let first = imports.len();
    let helpers = streams::Helpers::new(&plan, &streams, first + constants.len() as u32);

    // generate a function returning each value
    let mut functions = FunctionSection::new();
    let mut code = CodeSection::new();
    let mut exports = ExportSection::new();
    let mut stream_index = 0;
    for (index, (constant, body)) in constants.iter().zip(&bodies).enumerate() {
        let func = constant.func;
        functions.function(index as u32);
        let mut abi = LiftLowerAbi::Sync;
        let mut callback = None;
        match body {
            Body::Flat(_, flat) => {
                let mut body = Function::new([]);
                for value in flat {
                    body.instruction(&match *value {
                        Flat::I32(v) => Instruction::I32Const(v),
                        Flat::I64(v) => Instruction::I64Const(v),
                        Flat::F32(v) => Instruction::F32Const(Ieee32::new(v)),
                        Flat::F64(v) => Instruction::F64Const(Ieee64::new(v)),
                    });
                }
                body.instruction(&Instruction::End);
                code.function(&body);
            }
            Body::Stream(_) => {
                code.function(&helpers.export(&streams, stream_index));
                callback = helpers.callback(stream_index);
                if callback.is_some() {
                    abi = LiftLowerAbi::AsyncCallback;
                }
                stream_index += 1;
            }
        }

        let export = |kind| {
            resolve.wasm_export_name(
                ManglingAndAbi::Legacy(abi),
                WasmExport::Func {
                    interface: constant.interface,
                    func,
                    kind,
                },
            )
        };
        exports.export(
            &export(WasmExportKind::Normal),
            ExportKind::Func,
            first + index as u32,
        );
        if let Some(callback) = callback {
            exports.export(
                &export(WasmExportKind::Callback),
                ExportKind::Func,
                callback,
            );
        }
    }
    for (ty, body) in helpers.functions(&streams, &mut types) {
        functions.function(ty);
        code.function(&body);
    }

    let mut memories = MemorySection::new();
    let memory_size = (layout.base() as u64 + layout.data().len() as u64).max(1);
    memories.memory(MemoryType {
        minimum: memory_size.div_ceil(PAGE_SIZE),
        maximum: None,
        memory64: false,
        shared: false,
        page_size_log2: None,
    });
    exports.export("memory", ExportKind::Memory, 0);

    let mut data = DataSection::new();
    data.active(
        0,
        &ConstExpr::i32_const(layout.base() as i32),
        layout.data().iter().copied(),
    );

    let mut producers = Producers::default();
    producers.add(
        "processed-by",
        "componentized-constants",
        env!("CARGO_PKG_VERSION"),
    );
    let component_type =
        metadata::encode(resolve, world, StringEncoding::UTF8, Some(&producers), true)?;

    let globals = helpers.globals(layout.base() + layout.data().len() as u32);

    let mut module = Module::new();
    module.section(types.section());
    if imports.len() > 0 {
        module.section(imports.section());
    }
    module.section(&functions);
    module.section(&memories);
    if let Some(globals) = &globals {
        module.section(globals);
    }
    module.section(&exports);
    module.section(&code);
    module.section(&data);
    module.section(&CustomSection {
        name: format!("component-type:{}", resolve.worlds[world].name).into(),
        data: component_type.into(),
    });
    Ok(module.finish())
}

/// The names of the function's arguments in expressions, as Rust names them,
/// e.g. `start_value` for `start-value`.
fn arg_names(func: &wit_parser::Function) -> Vec<String> {
    func.params
        .iter()
        .map(|p| p.name.replace('-', "_"))
        .collect()
}

/// The types of `$init`, the function's arguments, which must be integers,
/// floats or `bool`.
fn seed_types(resolve: &Resolve, func: &wit_parser::Function) -> Result<Vec<expr::Prim>> {
    if func.params.is_empty() {
        bail!("`$init` holds the function's arguments, but the function takes none");
    }
    func.params
        .iter()
        .map(|param| {
            expr::Prim::from_type(resolve, &param.ty).with_context(|| {
                format!(
                    "parameter `{}` can't be read with `$init`, its type must be an integer, \
                     float or bool",
                    param.name
                )
            })
        })
        .collect()
}

/// A function generating a stream from its arguments must be async, and take
/// at most 16 parameters.
fn check_arguments(resolve: &Resolve, func: &wit_parser::Function) -> Result<()> {
    if !matches!(func.kind, FunctionKind::AsyncFreestanding) {
        bail!(
            "a stream generated from arguments must be returned by an async function, e.g. \
             `async func(n: u8) -> stream<u8>`"
        );
    }
    if resolve
        .wasm_signature(AbiVariant::GuestExportAsync, func)
        .indirect_params
    {
        bail!("a stream can be generated from at most 16 arguments");
    }
    Ok(())
}

/// A stream generated from the arguments of `func`, which must be async and
/// take a parameter of the stream's item type for each of the expression's.
fn arguments_stream<'a>(
    resolve: &Resolve,
    interface: Option<&'a WorldKey>,
    func: &'a wit_parser::Function,
    ty: wit_parser::TypeId,
    generator: expr::Generator,
) -> Result<streams::Stream<'a>> {
    check_arguments(resolve, func)?;
    let params = func.params.len() as u32;
    if params != generator.params {
        let count = |n| match n {
            1 => "1 parameter".to_string(),
            n => format!("{n} parameters"),
        };
        bail!(
            "the expression takes {}, the function takes {}",
            count(generator.params),
            count(params)
        );
    }
    for param in &func.params {
        if expr::Prim::from_type(resolve, &param.ty) != Some(generator.item) {
            bail!(
                "parameter `{}` must have the stream's item type, `{}`",
                param.name,
                generator.item.name()
            );
        }
    }
    Ok(streams::Stream {
        interface,
        func,
        ty,
        ptr: 0,
        len: 0,
        stride: generator.item.size(),
        args: params,
        generator: Some(generator),
    })
}

/// Whether the WAVE source contains nothing but whitespace and comments.
fn is_blank(src: &str) -> bool {
    src.lines()
        .map(str::trim)
        .all(|line| line.is_empty() || line.starts_with("//"))
}

fn qualified_name(
    resolve: &Resolve,
    interface: Option<&WorldKey>,
    func: &wit_parser::Function,
) -> String {
    match interface {
        Some(key) => format!("{}#{}", resolve.name_world_key(key), func.name),
        None => func.name.clone(),
    }
}

/// The field name used for an export in the values record.
fn export_label(resolve: &Resolve, key: &WorldKey) -> Result<String> {
    Ok(match key {
        WorldKey::Name(name) => name.clone(),
        WorldKey::Interface(id) => resolve.interfaces[*id]
            .name
            .clone()
            .context("exported interfaces must be named")?,
    })
}

fn val_type(ty: &WasmType) -> ValType {
    match ty {
        WasmType::I32 | WasmType::Pointer | WasmType::Length => ValType::I32,
        WasmType::I64 | WasmType::PointerOrI64 => ValType::I64,
        WasmType::F32 => ValType::F32,
        WasmType::F64 => ValType::F64,
    }
}
