//! Exports returning a `stream<T>`, whose value is written as a list of the
//! stream's items.
//!
//! An empty stream is created and closed by a synchronous export, returning the
//! readable end. A stream with items needs a task that outlives the call, so the
//! export must be an `async func`. It's lifted with a callback: the export
//! creates the stream, returns the readable end with `task.return`, then writes
//! the items from the data segment, waiting whenever the reader hasn't taken
//! them all. The task ends once every item is written or the reader drops the
//! stream.
//!
//! A stream may continue past its listed items with items generated by an
//! `@expression`, see [`crate::expr`]. The listed items are written first, then
//! batches of generated items, until an item can't be generated or the reader
//! drops the stream.
//!
//! Each task's state is a record in linear memory, allocated from a free list
//! and kept in the task's context slot:
//!
//! ```text
//! offset 0: the waitable set the task waits on
//! offset 4: the number of listed items left to write
//! ```
//!
//! A generated stream's record continues:
//!
//! ```text
//! offset 8:  the number of items generated into the buffer
//! offset 12: the number of generated items written
//! offset 16: 1 once no more items can be generated
//! offset 24: `$i`, the position of the next item generated, a u64
//! offset 32: `$init`, each of the function's arguments in 8 bytes
//! then:      the buffer, the previous items the expression reads followed by
//!            the batch of generated items
//! ```
//!
//! None of this is emitted unless an export returns a stream, so other
//! components are unchanged.

use wasm_encoder::{
    BlockType, ConstExpr, EntityType, Function, GlobalSection, GlobalType, ImportSection,
    InstructionSink, MemArg, TypeSection, ValType,
};
use wit_parser::{
    LiftLowerAbi, ManglingAndAbi, Resolve, StreamIntrinsic, Type, TypeDefKind, TypeId, WasmImport,
    WorldKey,
};

use crate::expr::Generator;
use crate::types::dealias;

/// `waitable-set.wait`'s callback code, the set is in the upper 28 bits.
const CALLBACK_WAIT: i32 = 2;
const CALLBACK_EXIT: i32 = 0;
/// The event delivered when a write to a stream finishes.
const EVENT_STREAM_WRITE: i32 = 3;
/// Returned by an async `stream.write` that hasn't finished yet.
const BLOCKED: i32 = -1;
/// A finished copy's result is the item count shifted over a 4-bit status, a
/// `COMPLETED` status is zero.
const COPY_STATUS_BITS: i32 = 4;
const COPY_STATUS_MASK: i32 = 0xf;

const SET: MemArg = MemArg {
    offset: 0,
    align: 2,
    memory_index: 0,
};
const REMAINING: MemArg = MemArg {
    offset: 4,
    align: 2,
    memory_index: 0,
};
const FILLED: MemArg = MemArg {
    offset: 8,
    align: 2,
    memory_index: 0,
};
const WRITTEN: MemArg = MemArg {
    offset: 12,
    align: 2,
    memory_index: 0,
};
const DONE: MemArg = MemArg {
    offset: 16,
    align: 2,
    memory_index: 0,
};
/// The position of the next item generated, `$i`.
pub const INDEX: u32 = 24;
/// The function's arguments, `$init`, each in 8 bytes.
pub const SEEDS: u32 = 32;
const INDEX_ARG: MemArg = MemArg {
    offset: INDEX as u64,
    align: 3,
    memory_index: 0,
};
/// The number of items generated at a time, rounded up to a multiple of the
/// items each evaluation of the expression generates.
const BATCH: u32 = 64;

/// The stream type and item type when `ty` is a stream with items, following
/// aliases.
pub fn stream_type(resolve: &Resolve, ty: &Type) -> Option<(TypeId, Type)> {
    match dealias(resolve, *ty) {
        Type::Id(id) => match resolve.types[id].kind {
            TypeDefKind::Stream(Some(item)) => Some((id, item)),
            _ => None,
        },
        _ => None,
    }
}

/// An export returning a stream of `len` items stored from `ptr`, each `stride`
/// bytes, then any items the generator generates from the items before them.
pub struct Stream<'a> {
    pub interface: Option<&'a WorldKey>,
    pub func: &'a wit_parser::Function,
    pub ty: TypeId,
    pub ptr: u32,
    pub len: u32,
    pub stride: u32,
    /// The number of arguments the stream starts from, rather than listed
    /// items.
    pub args: u32,
    pub generator: Option<Generator>,
}

impl Stream<'_> {
    /// Whether the export writes items after returning the stream, rather
    /// than returning an empty, closed stream.
    pub fn is_async(&self) -> bool {
        self.len > 0 || self.generator.is_some()
    }

    /// The core type of each of the function's arguments, `$init`, or the
    /// items the stream starts from.
    pub fn params(&self) -> Vec<ValType> {
        match &self.generator {
            Some(generator) if !generator.seeds.is_empty() => {
                generator.seeds.iter().map(|ty| ty.val_type()).collect()
            }
            Some(generator) => vec![generator.item.val_type(); self.args as usize],
            None => vec![],
        }
    }

    /// Where the buffer starts in the task's state record, after the seeds.
    fn buffer(&self) -> u32 {
        let seeds = self.generator.as_ref().map_or(0, |g| g.seeds.len() as u32);
        SEEDS + 8 * seeds
    }

    fn end(&self) -> u32 {
        self.ptr + self.len * self.stride
    }

    /// The size of the task's state record.
    fn state_size(&self) -> u32 {
        match &self.generator {
            Some(generator) => (self.buffer()
                + (generator.params + batch(generator)) * self.stride)
                .next_multiple_of(8),
            None => 8,
        }
    }
}

/// The functions an export uses, by index.
struct Intrinsics {
    new: u32,
    drop_writable: u32,
    write: Option<u32>,
    task_return: Option<u32>,
}

/// Core functions the module imports, the async built-ins and each stream's
/// intrinsics.
pub struct Imports {
    section: ImportSection,
    /// The module and name of each import, by index. There are few, so they're
    /// searched rather than hashed.
    names: Vec<(String, String)>,
}

impl Imports {
    pub fn new() -> Self {
        Self {
            section: ImportSection::new(),
            names: vec![],
        }
    }

    pub fn len(&self) -> u32 {
        self.names.len() as u32
    }

    pub fn section(&self) -> &ImportSection {
        &self.section
    }

    fn import(
        &mut self,
        types: &mut Types,
        (module, name): (String, String),
        params: &[ValType],
        results: &[ValType],
    ) -> u32 {
        let import = (module, name);
        if let Some(index) = self.names.iter().position(|i| *i == import) {
            return index as u32;
        }
        let ty = types.intern(params, results);
        self.section
            .import(&import.0, &import.1, EntityType::Function(ty));
        self.names.push(import);
        self.names.len() as u32 - 1
    }

    fn root(
        &mut self,
        types: &mut Types,
        name: &str,
        params: &[ValType],
        results: &[ValType],
    ) -> u32 {
        self.import(types, ("$root".into(), name.into()), params, results)
    }
}

/// The type section, a function type for each constant followed by types
/// shared by the imports and helper functions.
pub struct Types {
    section: TypeSection,
    count: u32,
    /// Types shared by imports and helpers, searched rather than hashed.
    interned: Vec<(Vec<ValType>, Vec<ValType>, u32)>,
}

impl Types {
    pub fn new() -> Self {
        Self {
            section: TypeSection::new(),
            count: 0,
            interned: vec![],
        }
    }

    pub fn section(&self) -> &TypeSection {
        &self.section
    }

    /// Adds a function type, returning its index.
    pub fn push(&mut self, params: &[ValType], results: &[ValType]) -> u32 {
        self.section
            .ty()
            .function(params.iter().copied(), results.iter().copied());
        self.count += 1;
        self.count - 1
    }

    /// Adds a function type unless an identical type was interned already.
    fn intern(&mut self, params: &[ValType], results: &[ValType]) -> u32 {
        if let Some((.., index)) = self
            .interned
            .iter()
            .find(|(p, r, _)| p == params && r == results)
        {
            return *index;
        }
        let index = self.push(params, results);
        self.interned
            .push((params.to_vec(), results.to_vec(), index));
        index
    }
}

/// Built-ins shared by every async stream export.
struct Builtins {
    waitable_set_new: u32,
    waitable_set_drop: u32,
    waitable_join: u32,
    context_get: u32,
    context_set: u32,
}

/// Imports the functions the streams use, before any other function is
/// defined as imports come first in the function index space.
pub struct Plan {
    intrinsics: Vec<Intrinsics>,
    builtins: Option<Builtins>,
}

impl Plan {
    pub fn new(
        resolve: &Resolve,
        streams: &[&Stream],
        types: &mut Types,
        imports: &mut Imports,
    ) -> Self {
        use ValType::{I32, I64};
        let intrinsics = streams
            .iter()
            .map(|stream| {
                let name = |intrinsic, async_| {
                    resolve.wasm_import_name(
                        ManglingAndAbi::Legacy(LiftLowerAbi::Sync),
                        WasmImport::StreamIntrinsic {
                            interface: stream.interface,
                            func: stream.func,
                            ty: Some(stream.ty),
                            intrinsic,
                            exported: true,
                            async_,
                        },
                    )
                };
                let new = imports.import(types, name(StreamIntrinsic::New, false), &[], &[I64]);
                let drop_writable = imports.import(
                    types,
                    name(StreamIntrinsic::DropWritable, false),
                    &[I32],
                    &[],
                );
                let (write, task_return) = match stream.is_async() {
                    false => (None, None),
                    true => {
                        let write = imports.import(
                            types,
                            name(StreamIntrinsic::Write, true),
                            &[I32, I32, I32],
                            &[I32],
                        );
                        let module = match stream.interface {
                            Some(key) => format!("[export]{}", resolve.name_world_key(key)),
                            None => "[export]$root".to_string(),
                        };
                        let task_return = imports.import(
                            types,
                            (module, format!("[task-return]{}", stream.func.name)),
                            &[I32],
                            &[],
                        );
                        (Some(write), Some(task_return))
                    }
                };
                Intrinsics {
                    new,
                    drop_writable,
                    write,
                    task_return,
                }
            })
            .collect();
        let builtins = streams.iter().any(|s| s.is_async()).then(|| Builtins {
            waitable_set_new: imports.root(types, "[waitable-set-new]", &[], &[I32]),
            waitable_set_drop: imports.root(types, "[waitable-set-drop]", &[I32], &[]),
            waitable_join: imports.root(types, "[waitable-join]", &[I32, I32], &[]),
            context_get: imports.root(types, "[context-get-0]", &[], &[I32]),
            context_set: imports.root(types, "[context-set-0]", &[I32], &[]),
        });
        Self {
            intrinsics,
            builtins,
        }
    }
}

/// Emits the helper functions following the constants, `first` is the index
/// of the first helper.
pub struct Helpers<'p> {
    plan: &'p Plan,
    alloc: u32,
    free: u32,
    /// The size of every state record, the largest any stream needs.
    state_size: u32,
    /// The functions of each async stream, by stream.
    async_funcs: Vec<Option<AsyncFuncs>>,
}

/// The functions writing an async stream, by index.
#[derive(Clone, Copy)]
struct AsyncFuncs {
    pump: u32,
    callback: u32,
    /// Generates an item, for a stream with a generator.
    generate: Option<u32>,
}

impl<'p> Helpers<'p> {
    pub fn new(plan: &'p Plan, streams: &[&Stream], first: u32) -> Self {
        let mut next = first + 2;
        let mut take = || {
            next += 1;
            next - 1
        };
        let async_funcs = streams
            .iter()
            .map(|stream| {
                stream.is_async().then(|| AsyncFuncs {
                    pump: take(),
                    callback: take(),
                    generate: stream.generator.as_ref().map(|_| take()),
                })
            })
            .collect();
        let state_size = streams.iter().map(|s| s.state_size()).max().unwrap_or(8);
        Self {
            plan,
            alloc: first,
            free: first + 1,
            state_size,
            async_funcs,
        }
    }

    /// The callback to export with the stream's export, when it's async.
    pub fn callback(&self, index: usize) -> Option<u32> {
        self.async_funcs[index].map(|funcs| funcs.callback)
    }

    /// The export returning the stream at `index`.
    pub fn export(&self, streams: &[&Stream], index: usize) -> Function {
        let stream = streams[index];
        let intrinsics = &self.plan.intrinsics[index];
        // locals follow the arguments
        let params = stream.params().len() as u32;
        let (pair, state, writable) = (params, params + 1, params + 2);
        let mut f = Function::new([(1, ValType::I64), (2, ValType::I32)]);
        let i = &mut f.instructions();
        // the writable end is in the upper 32 bits, the readable end the lower
        i.call(intrinsics.new)
            .local_tee(pair)
            .i64_const(32)
            .i64_shr_u()
            .i32_wrap_i64()
            .local_set(writable);
        match (self.async_funcs[index], &self.plan.builtins) {
            (Some(funcs), Some(builtins)) => {
                i.call(self.alloc)
                    .local_tee(state)
                    .call(builtins.waitable_set_new)
                    .i32_store(SET)
                    .local_get(state)
                    .i32_const(stream.len as i32)
                    .i32_store(REMAINING);
                if let Some(generator) = &stream.generator {
                    let buffer = stream.buffer();
                    for field in [WRITTEN, DONE] {
                        i.local_get(state).i32_const(0).i32_store(field);
                    }
                    // the position of the first item generated, after the items
                    // the stream starts from
                    i.local_get(state)
                        .i64_const((stream.len + stream.args) as i64)
                        .i64_store(INDEX_ARG);
                    // the arguments are `$init`, or the first batch, which the
                    // expression starts from once they're written
                    for (arg, ty) in generator.seeds.iter().enumerate() {
                        i.local_get(state).local_get(arg as u32);
                        ty.store(i, SEEDS + 8 * arg as u32);
                    }
                    let generated = buffer + generator.params * stream.stride;
                    for arg in 0..stream.args {
                        i.local_get(state).local_get(arg);
                        generator.item.store(i, generated + arg * stream.stride);
                    }
                    i.local_get(state)
                        .i32_const(stream.args as i32)
                        .i32_store(FILLED);
                    // otherwise, the expression starts from the last listed items
                    let window = generator.params * stream.stride;
                    if window > 0 && stream.args == 0 {
                        i.local_get(state)
                            .i32_const(buffer as i32)
                            .i32_add()
                            .i32_const((stream.end() - window) as i32)
                            .i32_const(window as i32)
                            .memory_copy(0, 0);
                    }
                }
                i.local_get(state)
                    .call(builtins.context_set)
                    .local_get(pair)
                    .i32_wrap_i64()
                    .call(intrinsics.task_return.expect("async stream"))
                    .local_get(state)
                    .local_get(writable)
                    .call(funcs.pump);
            }
            // an empty stream is closed before it's returned
            _ => {
                i.local_get(writable)
                    .call(intrinsics.drop_writable)
                    .local_get(pair)
                    .i32_wrap_i64();
            }
        }
        i.end();
        f
    }

    /// The functions following the constants, in index order: the allocator
    /// then each async stream's pump and callback, with their types.
    pub fn functions(&self, streams: &[&Stream], types: &mut Types) -> Vec<(u32, Function)> {
        use ValType::I32;
        let Some(builtins) = &self.plan.builtins else {
            return vec![];
        };
        let mut functions = vec![
            (types.intern(&[], &[I32]), self.alloc_fn()),
            (types.intern(&[I32], &[]), self.free_fn()),
        ];
        for (index, stream) in streams.iter().enumerate() {
            let Some(funcs) = self.async_funcs[index] else {
                continue;
            };
            let intrinsics = &self.plan.intrinsics[index];
            let pump = match (&stream.generator, funcs.generate) {
                (Some(generator), Some(generate)) => {
                    self.generated_pump_fn(stream, generator, generate, intrinsics, builtins)
                }
                _ => self.pump_fn(stream, intrinsics, builtins),
            };
            functions.push((types.intern(&[I32, I32], &[I32]), pump));
            functions.push((
                types.intern(&[I32, I32, I32], &[I32]),
                self.callback_fn(stream, funcs, builtins),
            ));
            if let Some(generator) = &stream.generator {
                functions.push((types.intern(&[I32, I32], &[I32]), generator.function()));
            }
        }
        functions
    }

    /// The globals the allocator uses, the free list and the top of the heap,
    /// which starts at `heap`, past the data.
    pub fn globals(&self, heap: u32) -> Option<GlobalSection> {
        self.plan.builtins.as_ref()?;
        let mut globals = GlobalSection::new();
        let ty = GlobalType {
            val_type: ValType::I32,
            mutable: true,
            shared: false,
        };
        globals.global(ty, &ConstExpr::i32_const(0));
        globals.global(ty, &ConstExpr::i32_const(heap.next_multiple_of(8) as i32));
        Some(globals)
    }

    /// Takes a state record from the free list, or from the top of the heap,
    /// growing memory when the heap reaches its end.
    fn alloc_fn(&self) -> Function {
        let (free_list, heap) = (0, 1);
        let p = 0;
        let mut f = Function::new([(1, ValType::I32)]);
        f.instructions()
            .global_get(free_list)
            .if_(BlockType::Result(ValType::I32))
            .global_get(free_list)
            .local_tee(p)
            .i32_load(SET)
            .global_set(free_list)
            .local_get(p)
            .else_()
            .global_get(heap)
            .local_tee(p)
            .i32_const(self.state_size as i32)
            .i32_add()
            .global_set(heap)
            .global_get(heap)
            .memory_size(0)
            .i32_const(16)
            .i32_shl()
            .i32_gt_u()
            .if_(BlockType::Empty)
            .i32_const(1)
            .memory_grow(0)
            .i32_const(-1)
            .i32_eq()
            .if_(BlockType::Empty)
            .unreachable()
            .end()
            .end()
            .local_get(p)
            .end()
            .end();
        f
    }

    /// Returns a state record to the free list.
    fn free_fn(&self) -> Function {
        let free_list = 0;
        let p = 0;
        let mut f = Function::new([]);
        f.instructions()
            .local_get(p)
            .global_get(free_list)
            .i32_store(SET)
            .local_get(p)
            .global_set(free_list)
            .end();
        f
    }

    /// `pump(state, writable) -> callback code` writes the items left, until a
    /// write blocks, then waits for it. Once every item is written, or the
    /// reader drops the stream, the stream is closed and the task exits.
    fn pump_fn(&self, stream: &Stream, intrinsics: &Intrinsics, builtins: &Builtins) -> Function {
        let (state, writable, remaining, result) = (0, 1, 2, 3);
        let end = stream.end();
        let mut f = Function::new([(2, ValType::I32)]);
        let i = &mut f.instructions();
        i.block(BlockType::Empty)
            .loop_(BlockType::Empty)
            .local_get(state)
            .i32_load(REMAINING)
            .local_tee(remaining)
            .i32_eqz()
            .br_if(1)
            // write the items left, which end the data
            .local_get(writable)
            .i32_const(end as i32)
            .local_get(remaining)
            .i32_const(stream.stride as i32)
            .i32_mul()
            .i32_sub()
            .local_get(remaining)
            .call(intrinsics.write.expect("async stream"))
            .local_tee(result)
            .i32_const(BLOCKED)
            .i32_eq()
            .if_(BlockType::Empty)
            .local_get(writable)
            .local_get(state)
            .i32_load(SET)
            .call(builtins.waitable_join)
            .local_get(state)
            .i32_load(SET)
            .i32_const(4)
            .i32_shl()
            .i32_const(CALLBACK_WAIT)
            .i32_or()
            .return_()
            .end();
        consume(i, state, result);
        i.br(0)
            .end()
            .end()
            // close the stream and free the task's state
            .local_get(writable)
            .i32_const(0)
            .call(builtins.waitable_join)
            .local_get(writable)
            .call(intrinsics.drop_writable)
            .local_get(state)
            .i32_load(SET)
            .call(builtins.waitable_set_drop)
            .local_get(state)
            .call(self.free)
            .i32_const(CALLBACK_EXIT)
            .end();
        f
    }

    /// `pump(state, writable) -> callback code` for a stream with a generator:
    /// writes the listed items left, then the generated items, generating
    /// another batch once the last is written. Waits whenever a write blocks.
    /// Once an item can't be generated and the items before it are written,
    /// or the reader drops the stream, the stream is closed and the task
    /// exits.
    fn generated_pump_fn(
        &self,
        stream: &Stream,
        generator: &Generator,
        generate: u32,
        intrinsics: &Intrinsics,
        builtins: &Builtins,
    ) -> Function {
        let (state, writable, remaining, result, filled, written, n) = (0, 1, 2, 3, 4, 5, 6);
        let stride = stream.stride as i32;
        let write = intrinsics.write.expect("async stream");
        let buffer = stream.buffer() as i32;
        let generated = buffer + (generator.params * stream.stride) as i32;
        // waits when the write in `result` blocks
        let wait = |i: &mut InstructionSink| {
            i.local_get(result)
                .i32_const(BLOCKED)
                .i32_eq()
                .if_(BlockType::Empty)
                .local_get(writable)
                .local_get(state)
                .i32_load(SET)
                .call(builtins.waitable_join)
                .local_get(state)
                .i32_load(SET)
                .i32_const(4)
                .i32_shl()
                .i32_const(CALLBACK_WAIT)
                .i32_or()
                .return_()
                .end();
        };
        let mut f = Function::new([(5, ValType::I32)]);
        let i = &mut f.instructions();
        i.block(BlockType::Empty).loop_(BlockType::Empty);

        // the listed items left, which end the data
        i.local_get(state)
            .i32_load(REMAINING)
            .local_tee(remaining)
            .if_(BlockType::Empty)
            .local_get(writable)
            .i32_const(stream.end() as i32)
            .local_get(remaining)
            .i32_const(stride)
            .i32_mul()
            .i32_sub()
            .local_get(remaining)
            .call(write)
            .local_set(result);
        wait(i);
        account(i, state, result);
        i.br(1).end();

        // the generated items left
        i.local_get(state)
            .i32_load(WRITTEN)
            .local_tee(written)
            .local_get(state)
            .i32_load(FILLED)
            .local_tee(filled)
            .i32_lt_u()
            .if_(BlockType::Empty)
            .local_get(writable)
            .local_get(state)
            .i32_const(generated)
            .i32_add()
            .local_get(written)
            .i32_const(stride)
            .i32_mul()
            .i32_add()
            .local_get(filled)
            .local_get(written)
            .i32_sub()
            .call(write)
            .local_set(result);
        wait(i);
        account(i, state, result);
        i.br(1).end();

        // every item is written
        i.local_get(state).i32_load(DONE).br_if(1);

        // the last items of the batch become the items the expression reads
        let window = (generator.params * stream.stride) as i32;
        if window > 0 {
            i.local_get(state)
                .i32_const(buffer)
                .i32_add()
                .local_get(state)
                .i32_const(buffer)
                .i32_add()
                .local_get(filled)
                .i32_const(stride)
                .i32_mul()
                .i32_add()
                .i32_const(window)
                .memory_copy(0, 0);
        }

        // generate a batch, stopping at items that can't be generated, each
        // evaluation generating `count` items
        let count = generator.count as i32;
        i.i32_const(0)
            .local_set(n)
            .block(BlockType::Empty)
            .loop_(BlockType::Empty)
            .local_get(n)
            .i32_const(batch(generator) as i32)
            .i32_eq()
            .br_if(1)
            .local_get(state)
            .local_get(state)
            .i32_const(buffer)
            .i32_add()
            .local_get(n)
            .i32_const(stride)
            .i32_mul()
            .i32_add()
            .call(generate)
            .i32_eqz()
            .if_(BlockType::Empty)
            .local_get(state)
            .i32_const(1)
            .i32_store(DONE)
            .br(2)
            .end()
            .local_get(n)
            .i32_const(count)
            .i32_add()
            .local_set(n)
            // the next position, the stream ends after the items at the last
            // positions, when the position wraps
            .local_get(state)
            .local_get(state)
            .i64_load(INDEX_ARG)
            .i64_const(count as i64)
            .i64_add()
            .i64_store(INDEX_ARG)
            .local_get(state)
            .i64_load(INDEX_ARG)
            .i64_const(count as i64)
            .i64_lt_u()
            .if_(BlockType::Empty)
            .local_get(state)
            .i32_const(1)
            .i32_store(DONE)
            .br(2)
            .end()
            .br(0)
            .end()
            .end()
            .local_get(state)
            .local_get(n)
            .i32_store(FILLED)
            .local_get(state)
            .i32_const(0)
            .i32_store(WRITTEN)
            .br(0)
            .end()
            .end();

        // close the stream and free the task's state
        i.local_get(writable)
            .i32_const(0)
            .call(builtins.waitable_join)
            .local_get(writable)
            .call(intrinsics.drop_writable)
            .local_get(state)
            .i32_load(SET)
            .call(builtins.waitable_set_drop)
            .local_get(state)
            .call(self.free)
            .i32_const(CALLBACK_EXIT)
            .end();
        f
    }

    /// `callback(event, writable, result) -> callback code` accounts for the
    /// finished write then pumps the items left.
    fn callback_fn(&self, stream: &Stream, funcs: AsyncFuncs, builtins: &Builtins) -> Function {
        let (event, writable, result, state) = (0, 1, 2, 3);
        let mut f = Function::new([(1, ValType::I32)]);
        let i = &mut f.instructions();
        i.local_get(event)
            .i32_const(EVENT_STREAM_WRITE)
            .i32_ne()
            .if_(BlockType::Empty)
            .unreachable()
            .end()
            .call(builtins.context_get)
            .local_set(state);
        match stream.generator {
            Some(_) => account(i, state, result),
            None => consume(i, state, result),
        }
        i.local_get(state)
            .local_get(writable)
            .call(funcs.pump)
            .end();
        f
    }
}

/// The number of items generated at a time, a multiple of the items each
/// evaluation generates.
fn batch(generator: &Generator) -> u32 {
    BATCH.next_multiple_of(generator.count)
}

/// Accounts for a finished write of a stream with a generator: the items it
/// copied were listed items while any are left, otherwise generated items.
/// When the reader dropped the stream, nothing is left to write.
fn account(i: &mut InstructionSink, state: u32, result: u32) {
    i.local_get(result)
        .i32_const(COPY_STATUS_MASK)
        .i32_and()
        .if_(BlockType::Empty);
    for field in [REMAINING, FILLED, WRITTEN] {
        i.local_get(state).i32_const(0).i32_store(field);
    }
    i.local_get(state)
        .i32_const(1)
        .i32_store(DONE)
        .else_()
        .local_get(state)
        .i32_load(REMAINING)
        .if_(BlockType::Empty)
        .local_get(state)
        .local_get(state)
        .i32_load(REMAINING)
        .local_get(result)
        .i32_const(COPY_STATUS_BITS)
        .i32_shr_u()
        .i32_sub()
        .i32_store(REMAINING)
        .else_()
        .local_get(state)
        .local_get(state)
        .i32_load(WRITTEN)
        .local_get(result)
        .i32_const(COPY_STATUS_BITS)
        .i32_shr_u()
        .i32_add()
        .i32_store(WRITTEN)
        .end()
        .end();
}

/// Subtracts the items a finished write copied from the items left, or leaves
/// none when the reader dropped the stream.
fn consume(i: &mut InstructionSink, state: u32, result: u32) {
    i.local_get(state)
        .local_get(state)
        .i32_load(REMAINING)
        .local_get(result)
        .i32_const(COPY_STATUS_BITS)
        .i32_shr_u()
        .i32_sub()
        .i32_const(0)
        .local_get(result)
        .i32_const(COPY_STATUS_MASK)
        .i32_and()
        .i32_eqz()
        .select()
        .i32_store(REMAINING);
}
