/// Constants for the `u8` unsigned integer type.
interface %u8 {
    /// u8 max value
    /// @value 255
    max: func() -> u8;

    /// u8 min value
    /// @value 0
    min: func() -> u8;

    /// The size of `u8` in bits.
    /// @value 8
    bits: func() -> u32;
}

/// Constants for the `u16` unsigned integer type.
interface %u16 {
    /// u16 max value
    /// @value 65535
    max: func() -> u16;

    /// u16 min value
    /// @value 0
    min: func() -> u16;

    /// The size of `u16` in bits.
    /// @value 16
    bits: func() -> u32;
}

/// Constants for the `u32` unsigned integer type.
interface %u32 {
    /// u32 max value
    /// @value 4294967295
    max: func() -> u32;

    /// u32 min value
    /// @value 0
    min: func() -> u32;

    /// The size of `u32` in bits.
    /// @value 32
    bits: func() -> u32;
}

/// Constants for the `u64` unsigned integer type.
interface %u64 {
    /// u64 max value
    /// @value 18446744073709551615
    max: func() -> u64;

    /// u64 min value
    /// @value 0
    min: func() -> u64;

    /// The size of `u64` in bits.
    /// @value 64
    bits: func() -> u32;
}

/// Constants for the `s8` signed integer type.
interface %s8 {
    /// s8 max value
    /// @value 127
    max: func() -> s8;

    /// s8 min value
    /// @value -128
    min: func() -> s8;

    /// The size of `s8` in bits.
    /// @value 8
    bits: func() -> u32;
}

/// Constants for the `s16` signed integer type.
interface %s16 {
    /// s16 max value
    /// @value 32767
    max: func() -> s16;

    /// s16 min value
    /// @value -32768
    min: func() -> s16;

    /// The size of `s16` in bits.
    /// @value 16
    bits: func() -> u32;
}

/// Constants for the `s32` signed integer type.
interface %s32 {
    /// s32 max value
    /// @value 2147483647
    max: func() -> s32;

    /// s32 min value
    /// @value -2147483648
    min: func() -> s32;

    /// The size of `s32` in bits.
    /// @value 32
    bits: func() -> u32;
}

/// Constants for the `s64` signed integer type.
interface %s64 {
    /// s64 max value
    /// @value 9223372036854775807
    max: func() -> s64;

    /// s64 min value
    /// @value -9223372036854775808
    min: func() -> s64;

    /// The size of `s64` in bits.
    /// @value 64
    bits: func() -> u32;
}

/// Constants for the `f32` floating point type.
interface %f32 {
    /// The radix or base of the internal representation of `f32`.
    /// @value 2
    radix: func() -> u32;

    /// Number of significant digits in base 2.
    /// @value 24
    mantissa-digits: func() -> u32;

    /// Approximate number of significant digits in base 10.
    /// @value 6
    digits: func() -> u32;

    /// Machine epsilon value for `f32`, the difference between `1.0` and the next larger representable number.
    /// @value 1.19209290e-07
    epsilon: func() -> f32;

    /// Smallest finite `f32` value.
    /// @value -3.40282347e+38
    min: func() -> f32;

    /// Smallest positive normal `f32` value.
    /// @value 1.17549435e-38
    min-positive: func() -> f32;

    /// Largest finite `f32` value.
    /// @value 3.40282347e+38
    max: func() -> f32;

    /// One greater than the minimum possible normal power of 2 exponent.
    /// @value -125
    min-exp: func() -> s32;

    /// Maximum possible power of 2 exponent.
    /// @value 128
    max-exp: func() -> s32;

    /// Minimum *x* for which 10<sup>*x*</sup> is normal.
    /// @value -37
    min-n10-exp: func() -> s32;

    /// Maximum *x* for which 10<sup>*x*</sup> is normal.
    /// @value 38
    max-n10-exp: func() -> s32;

    /// Not a Number (NaN).
    /// @value nan
    nan: func() -> f32;

    /// Infinity (∞).
    /// @value inf
    infinity: func() -> f32;

    /// Negative infinity (−∞).
    /// @value -inf
    neg-infinity: func() -> f32;
}

/// Constants for the `f64` floating point type.
interface %f64 {
    /// The radix or base of the internal representation of `f64`.
    /// @value 2
    radix: func() -> u32;

    /// Number of significant digits in base 2.
    /// @value 53
    mantissa-digits: func() -> u32;

    /// Approximate number of significant digits in base 10.
    /// @value 15
    digits: func() -> u32;

    /// Machine epsilon value for `f64`, the difference between `1.0` and the next larger representable number.
    /// @value 2.2204460492503131e-16
    epsilon: func() -> f64;

    /// Smallest finite `f64` value.
    /// @value -1.7976931348623157e+308
    min: func() -> f64;

    /// Smallest positive normal `f64` value.
    /// @value 2.2250738585072014e-308
    min-positive: func() -> f64;

    /// Largest finite `f64` value.
    /// @value 1.7976931348623157e+308
    max: func() -> f64;

    /// One greater than the minimum possible normal power of 2 exponent.
    /// @value -1021
    min-exp: func() -> s32;

    /// Maximum possible power of 2 exponent.
    /// @value 1024
    max-exp: func() -> s32;

    /// Minimum *x* for which 10<sup>*x*</sup> is normal.
    /// @value -307
    min-n10-exp: func() -> s32;

    /// Maximum *x* for which 10<sup>*x*</sup> is normal.
    /// @value 308
    max-n10-exp: func() -> s32;

    /// Not a Number (NaN).
    /// @value nan
    nan: func() -> f64;

    /// Infinity (∞).
    /// @value inf
    infinity: func() -> f64;

    /// Negative infinity (−∞).
    /// @value -inf
    neg-infinity: func() -> f64;
}
