package componentized:constants-component;

world math {
    export componentized:constants/%u8@0.0.0-dev;
    export componentized:constants/%u16@0.0.0-dev;
    export componentized:constants/%u32@0.0.0-dev;
    export componentized:constants/%u64@0.0.0-dev;
    export componentized:constants/%s8@0.0.0-dev;
    export componentized:constants/%s16@0.0.0-dev;
    export componentized:constants/%s32@0.0.0-dev;
    export componentized:constants/%s64@0.0.0-dev;
    export componentized:constants/%f32@0.0.0-dev;
    export componentized:constants/%f64@0.0.0-dev;
}
