use anyhow::{Context, Result};
use clap::Parser;
use componentized_constants::{Overrides, create_component, load_world};
use std::{
    fs::File,
    io::{self, Read, Write},
    path::Path,
};

fn main() {
    if let Err(message) = Command::parse().exec() {
        eprintln!("{message:#}");
        std::process::exit(1);
    }
}

#[derive(Debug, Parser)]
#[command()]
/// Create a wasm component whose exported functions return constant values.
///
/// Every function exported by the world must accept no parameters and return a
/// value. Values can't reach maps, handles, futures, streams or error
/// contexts, though result types may include them in branches the value
/// doesn't take, e.g. `none` for an `option<own<r>>`. A function may return a
/// stream, written as a list of its items, which must be an async function
/// unless the stream is empty. A stream may continue with items generated by
/// a Rust closure following an `@expression` tag, e.g. `|a, b| a + b`, from
/// the items before them, ending once an item can't be represented. Instead of
/// a `@value`, the function may take the items the stream starts from as
/// arguments, e.g. `async func(a: u32, b: u32) -> stream<u32>`.
///
/// Each function's value is a WAVE expression following a `@value` tag in its
/// doc comment, e.g. `/// @value 42`.
struct Command {
    /// Output to a file, '-' for stdout
    #[arg(short('o'), long("output"), name("wasm-file"))]
    output: String,
    /// WIT file or directory defining the world to implement
    #[arg(short('w'), long("wit"), name("wit-path"))]
    wit: String,
    /// Name of the world to implement, required if the WIT package defines
    /// more than one world
    #[arg(long("world"), name("world"))]
    world: Option<String>,
    /// WAVE encoded overrides file, '-' for stdin. The file contains a
    /// record with an optional field for each export of the world, replacing
    /// the value from the `@value` doc tag.
    #[arg(short('f'), long("overrides"), name("overrides-file"))]
    overrides: Option<String>,
}

impl Command {
    fn exec(&self) -> Result<()> {
        let (resolve, world) = load_world(&self.wit, self.world.as_deref())?;

        let mut overrides = String::new();
        match self.overrides.as_deref() {
            None => {}
            Some("-") => {
                eprintln!("Reading overrides from stdin (ctrl-d to finish)");
                io::stdin().read_to_string(&mut overrides)?;
            }
            Some(path) => {
                eprintln!("Reading overrides from {path}");
                File::open(Path::new(path))
                    .and_then(|mut file| file.read_to_string(&mut overrides))
                    .with_context(|| format!("unable to read {path}"))?;
            }
        };

        let component = create_component(&resolve, world, Some(Overrides::Wave(&overrides)))?;

        let mut output = match self.output.as_str() {
            "-" => {
                eprintln!("Writing component to stdout");
                Box::new(io::stdout()) as Box<dyn Write>
            }
            path => {
                eprintln!("Writing component to {path}");
                Box::new(File::create(Path::new(path))?) as Box<dyn Write>
            }
        };
        output.write_all(&component)?;
        Ok(())
    }
}
